### ISSUE TITLE
How to deploy on netlify?

### ISSUE THREAD

**Issue by broskees** [mpolinowski/material-ui-gatsby-wiki#1]
Can I deploy the docker container and the node server for gatsby on netlify?

**Comment by mpolinowski** [comment]
Hey @broskees,

I have not yet worked with Netlify. But as I understand it, it just offers an API that you can use to upload static content (so gatsby builds)?

https://www.netlify.com/with/gatsby/

To work with this container directly, you will need to ssh into a server and set up Docker there, push your image into a Docker Registry (e.g. Docker Hub) and then pull it from your server (that is what I am using).

But what you might be rather looking for, is a host that runs Kubernetes - Amazon, Google Cloud, Azure.. etc. Push your image into a Docker Registry and pull it into your Kubernetes Cluster and it will just work.

**Comment by broskees** [comment]
What I ended up doing was replacing elasticsearch with a simpler search
system and then deploying to netlify using the process you outlined above.
I had never worked with elasticsearch so it was confusing me. I'm sure I
could have gotten it to work on netlify but I didn't want to invest the
time at this point. Thank you!

**Comment by mpolinowski** [comment]
Elasticsearch or the Docker workflow only works if you have Kubernetes or your own server with root ssh login. But if you want to give Elasticsearch a try without having to set it up - check out [Algolia](https://www.algolia.com). Basically Elasticsearch-as-a-Service.

Their free-tier was just a bit too limiting for my project ~ it might work for yours.
